//! Wavefront OBJ exporter with per-vertex normals.
//!
//! # Format
//! ```text
//! # comment
//! v  x y z        (one per vertex)
//! vn nx ny nz     (one per vertex, area-weighted average of face normals)
//! f  a//na b//nb c//nc   (1-indexed; same index for position and normal)
//! ```
//! OBJ is a widely supported ASCII format readable by Blender, MeshLab, and
//! most CAD tools.  Per-vertex normals allow smooth shading of meshes with
//! relatively low triangle counts.

use glam::Vec3;

use crate::error::Result;
use crate::mesher::Mesh;

use super::compute_vertex_normals;

/// Serialize `mesh` to Wavefront OBJ text bytes.
pub fn to_bytes(mesh: &Mesh) -> Result<Vec<u8>> {
    let normals = compute_vertex_normals(&mesh.vertices, &mesh.triangles);

    let mut s = String::with_capacity(mesh.vertex_count() * 40 + mesh.triangle_count() * 30);

    s.push_str("# Generated by polyhedra\n");
    s.push_str("# https://github.com/polyhedra/polyhedra\n");
    s.push_str("o mesh\n");

    // Vertex positions.
    for v in &mesh.vertices {
        push_vec3(&mut s, "v", *v);
    }

    // Vertex normals.
    for n in &normals {
        push_vec3(&mut s, "vn", *n);
    }

    // Faces — 1-indexed, same index for position and normal.
    for &[a, b, c] in &mesh.triangles {
        let (a, b, c) = (a + 1, b + 1, c + 1);
        s.push_str(&format!("f {a}//{a} {b}//{b} {c}//{c}\n"));
    }

    Ok(s.into_bytes())
}

#[inline]
fn push_vec3(s: &mut String, prefix: &str, v: Vec3) {
    s.push_str(&format!("{prefix} {:.6} {:.6} {:.6}\n", v.x, v.y, v.z));
}
