//! Binary STL exporter.
//!
//! # Format
//! ```text
//! [80 bytes]  ASCII header
//! [4  bytes]  triangle count (uint32 LE)
//! Per triangle (50 bytes):
//!   [12 bytes] face normal (3 × f32 LE)
//!   [12 bytes] vertex 0   (3 × f32 LE)
//!   [12 bytes] vertex 1   (3 × f32 LE)
//!   [12 bytes] vertex 2   (3 × f32 LE)
//!   [2  bytes] attribute  (uint16 = 0)
//! ```
//! Binary STL is universally supported and the most compact non-compressed
//! triangle mesh format for exchange with slicer and CAM software.

use std::io::Write;

use glam::Vec3;

use crate::mesher::Mesh;
use crate::error::Result;

const HEADER: &[u8; 80] =
    b"Generated by polyhedra                                                          ";

/// Serialize `mesh` to binary STL bytes.
pub fn to_bytes(mesh: &Mesh) -> Result<Vec<u8>> {
    let n_tri = mesh.triangle_count();
    let mut buf: Vec<u8> = Vec::with_capacity(84 + 50 * n_tri);

    // ── Header ───────────────────────────────────────────────────────────────
    buf.write_all(HEADER)?;
    buf.write_all(&(n_tri as u32).to_le_bytes())?;

    // ── Triangles ─────────────────────────────────────────────────────────────
    for &[ai, bi, ci] in &mesh.triangles {
        let va = mesh.vertices[ai as usize];
        let vb = mesh.vertices[bi as usize];
        let vc = mesh.vertices[ci as usize];

        // Face normal (outward).
        let normal = (vb - va).cross(vc - va).normalize_or_zero();
        write_vec3(&mut buf, normal)?;
        write_vec3(&mut buf, va)?;
        write_vec3(&mut buf, vb)?;
        write_vec3(&mut buf, vc)?;

        // Attribute byte count = 0.
        buf.write_all(&0u16.to_le_bytes())?;
    }

    Ok(buf)
}

#[inline]
fn write_vec3(buf: &mut Vec<u8>, v: Vec3) -> Result<()> {
    buf.write_all(&v.x.to_le_bytes())?;
    buf.write_all(&v.y.to_le_bytes())?;
    buf.write_all(&v.z.to_le_bytes())?;
    Ok(())
}
