//! Binary PLY (Polygon File Format) exporter — little-endian.
//!
//! # Header (ASCII)
//! ```text
//! ply
//! format binary_little_endian 1.0
//! comment Generated by polyhedra
//! element vertex N
//! property float x
//! property float y
//! property float z
//! property float nx
//! property float ny
//! property float nz
//! element face M
//! property list uchar int vertex_indices
//! end_header
//! ```
//!
//! # Binary body
//! - N vertices × 24 bytes: (x, y, z, nx, ny, nz) as f32 LE
//! - M faces × 13 bytes: (3 as u8), (a, b, c as i32 LE)
//!
//! PLY is supported by MeshLab, Blender, CloudCompare, and Open3D.

use std::io::Write;

use glam::Vec3;

use crate::mesher::Mesh;
use crate::error::Result;

use super::compute_vertex_normals;

/// Serialize `mesh` to binary PLY bytes.
pub fn to_bytes(mesh: &Mesh) -> Result<Vec<u8>> {
    let nv    = mesh.vertex_count();
    let nf    = mesh.triangle_count();
    let normals = compute_vertex_normals(&mesh.vertices, &mesh.triangles);

    // ── ASCII header ──────────────────────────────────────────────────────────
    let header = format!(
        "ply\n\
         format binary_little_endian 1.0\n\
         comment Generated by polyhedra\n\
         element vertex {nv}\n\
         property float x\n\
         property float y\n\
         property float z\n\
         property float nx\n\
         property float ny\n\
         property float nz\n\
         element face {nf}\n\
         property list uchar int vertex_indices\n\
         end_header\n"
    );

    let capacity = header.len() + nv * 24 + nf * 13;
    let mut buf: Vec<u8> = Vec::with_capacity(capacity);
    buf.write_all(header.as_bytes())?;

    // ── Vertex data ───────────────────────────────────────────────────────────
    for (v, n) in mesh.vertices.iter().zip(normals.iter()) {
        write_f32(&mut buf, v.x)?;
        write_f32(&mut buf, v.y)?;
        write_f32(&mut buf, v.z)?;
        write_f32(&mut buf, n.x)?;
        write_f32(&mut buf, n.y)?;
        write_f32(&mut buf, n.z)?;
    }

    // ── Face data ─────────────────────────────────────────────────────────────
    for &[a, b, c] in &mesh.triangles {
        buf.push(3u8); // vertex count per face
        write_i32(&mut buf, a as i32)?;
        write_i32(&mut buf, b as i32)?;
        write_i32(&mut buf, c as i32)?;
    }

    Ok(buf)
}

#[inline]
fn write_f32(buf: &mut Vec<u8>, v: f32) -> Result<()> {
    buf.write_all(&v.to_le_bytes())?;
    Ok(())
}

#[inline]
fn write_i32(buf: &mut Vec<u8>, v: i32) -> Result<()> {
    buf.write_all(&v.to_le_bytes())?;
    Ok(())
}
